version: "2.0"
services:
  nginx-php-fpm:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: php_container
    restart: always
    ports:
        - 8080:80
    volumes:
      - ./src:/var/www/somePhp

  mysql_container:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev
        MYSQL_DATABASE: forthelulz
    ports:
        - "3308:3306"
    restart: always
    volumes:
        - ./mysql-data:/var/lib/mysql
