version: "2.0"
services:
  nginx-php-fpm:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: php_container
    restart: always
    ports:
        - 8080:80
    volumes:
      - ./src:/var/www/awesomeShop

  mysql_container:
    build:
      context: ./
      dockerfile: DockerfileMysql
    environment:
        MYSQL_ROOT_PASSWORD: dev
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev
        MYSQL_DATABASE: awesomeShop
    ports:
        - "3308:3306"
    restart: always
    volumes:
        - ./mysql-data:/var/lib/mysql
